name: smart_learning_application
description: "PMDEduMind — AI study workspace (Flutter)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.0
  youtube_explode_dart: ^3.1.0
  flutter_gemini: ^2.0.4
  image_picker: ^1.1.2
  dash_chat_2: ^0.0.21
  cached_network_image: ^3.3.1
  flutter_swiper_null_safety: ^1.0.2
  provider: ^6.1.2
  shared_preferences: ^2.5.5
  percent_indicator: ^4.2.5
  smooth_page_indicator: ^2.0.1

  kalender:
    path: ./kalender
  web_demo:
    path: ./kalender/examples/web_demo
  flutter_gen: ^5.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  intl: ^0.20.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/assets/profile_icon.jpg
